version: '3.9'

services:
  wordpress: 
    build:
      context: .
      dockerfile: prod.wp.Dockerfile
    ports:
      - "${HOST_HTTP_PORT}:80"
      - "${HOST_HTTPS_PORT}:443"
    # volumes:
    #   - ./ssl:/etc/etc/apache2/ssl-certs:ro
    hostname: pikloo-dev.online
    # links:
    #   - "maildev:maildev"
    
  # maildev:
  #   image: maildev/maildev
  #   container_name: wp_maildev
  #   command: bin/maildev --web 80 --smtp 25 #--hide-extensions STARTTLS
  #   ports:
  #     - "1080:80" # Interface web
  #     - "1025:25" # SMTP
  #   restart: always
  #   networks:
  #     - wp