version: "3.9"
# @link https://github.com/eewee/docker-wordpress-phpmyadmin/blob/master/docker-compose.yml
# @link https://www.leonpahole.com/blog/post/dockerizing-wordpress/

services:
  # CONTAINER - MYSQL : https://hub.docker.com/_/mysql
  db:
    image: mariadb:latest
    container_name: wp_mariadb
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    networks:
      - wp

  # CONTAINER - WORDPRESS : https://hub.docker.com/_/wordpress
  wordpress:
    depends_on:
      - db
    # image: wordpress:php8.3-apache
    build:
      context: .
      dockerfile: wp.Dockerfile
    container_name: wp_wordpress
    restart: always
    user: 0:0
    volumes:
      - ./website:/var/www/html
      - ./website/wp-content:/var/www/html/wp-content
    # command: bash -c "cd /var/www/html/wp-content/themes/encrage && npm run dev && npx tailwindcss -i ./input.css -o ./src/style.css --watch"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: "${MYSQL_USER}"
      WORDPRESS_DB_PASSWORD: "${MYSQL_PASSWORD}"
      WORDPRESS_DB_NAME: "${MYSQL_DATABASE}"
      WORDPRESS_TABLE_PREFIX: "${WORDPRESS_TABLE_PREFIX}"
    ports:
      - 80:80
      # - 433:433
    networks:
      - wp
    # links:
    #   - "maildev:maildev"

  # CONTAINER - PHPMYADMIN : https://hub.docker.com/r/phpmyadmin/phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin:latest
    container_name: wp_phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
    ports:
      - "8080:80"
    networks:
      - wp

  # maildev:
  #   image: maildev/maildev
  #   container_name: wp_maildev
  #   command: bin/maildev --web 80 --smtp 25 #--hide-extensions STARTTLS
  #   ports:
  #     - "1080:80" # Interface web
  #     - "1025:25" # SMTP
  #   restart: always
  #   networks:
  #     - wp

networks:
  wp:

volumes:
  db_data:
